#!/usr/bin/env python3
"""Build and install MDL as one Python source file (macOS/Linux)."""

import argparse
import os
import pprint
import shutil
import subprocess
import sys
import tempfile
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Sources stay in separate module namespaces, preserving imports and globals.
BOOTSTRAP = r"""
import importlib.abc
import importlib.util
import sys


class _EmbeddedModules(importlib.abc.MetaPathFinder, importlib.abc.SourceLoader):
    def find_spec(self, fullname, path=None, target=None):
        if fullname in _SOURCES:
            return importlib.util.spec_from_loader(fullname, self)
        return None

    def get_filename(self, fullname):
        return __file__ + "/" + _SOURCES[fullname][0]

    def get_source(self, fullname):
        return _SOURCES[fullname][1]

    def get_data(self, path):
        for name in _SOURCES:
            if path == self.get_filename(name):
                return self.get_source(name).encode("utf-8")
        raise OSError(path)

    def is_package(self, fullname):
        return _SOURCES[fullname][0].endswith("/__init__.py")


def _run():
    loader = _EmbeddedModules()
    sys.meta_path.insert(0, loader)
    namespace = {
        "__name__": "__main__",
        "__file__": __file__,
        "__package__": None,
        "__spec__": None,
        "__builtins__": __builtins__,
    }
    # The source-tree updater cannot update an installed bundle.
    import src.system_utils
    def update_bundle():
        print("To update this single-file installation, pull the MDL source "
              "and rerun install_single.py with the same installation options.")
    src.system_utils.update = update_bundle
    exec(compile(_MAIN, __file__ + "/main.py", "exec"), namespace)


if __name__ == "__main__":
    _run()
"""


def build(output: Path, python: str | None = None) -> None:
    """Collect application source, validate it, and atomically write a bundle."""
    sources = {}
    for path in sorted((ROOT / "src").rglob("*.py")):
        relative = path.relative_to(ROOT).as_posix()
        with tokenize.open(path) as stream:
            source = stream.read()
        compile(source, relative, "exec")
        parts = list(path.relative_to(ROOT).with_suffix("").parts)
        if parts[-1] == "__init__":
            parts.pop()
        sources[".".join(parts)] = (relative, source)
    if "src" not in sources:
        raise ValueError("Missing src/__init__.py; run from a complete checkout")
    with tokenize.open(ROOT / "main.py") as stream:
        main_source = stream.read()
    compile(main_source, "main.py", "exec")
    # env is used for portable build-only output; installed files pin Python.
    shebang = "#!/usr/bin/env python3"
    if python:
        if any(c.isspace() for c in python) or len(os.fsencode(python)) > 120:
            raise ValueError("Interpreter path must have no whitespace and be <=120 bytes")
        shebang = "#!" + python
    license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    content = (
        shebang
        + "\n# Generated by install_single.py; rebuild to update.\n"
        + "# Includes main.py and all src/**/*.py application sources.\n"
        + "_LICENSE = "
        + repr(license_text)
        + "\n"
        + "_SOURCES = "
        + pprint.pformat(sources, sort_dicts=True, width=100)
        + "\n"
        + "_MAIN = "
        + repr(main_source)
        + "\n"
        + BOOTSTRAP
    )
    compile(content, str(output), "exec")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=output.parent, delete=False
        ) as stream:
            temporary = Path(stream.name)
            stream.write(content)
        temporary.chmod(0o755)
        os.replace(temporary, output)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--build-only",
        action="store_true",
        help="Build without installing or downloading dependencies",
    )
    parser.add_argument("--output", type=Path, default=ROOT / "dist" / "mdl.py")
    parser.add_argument("--bin-dir", type=Path, default=Path.home() / ".local" / "bin")
    parser.add_argument(
        "--venv-dir", type=Path, default=Path.home() / ".local" / "share" / "mdl" / "venv"
    )
    parser.add_argument(
        "--skip-deps",
        action="store_true",
        help="Use this Python interpreter and its existing dependencies",
    )
    parser.add_argument(
        "--playwright", action="store_true", help="Also install Playwright Chromium"
    )
    args = parser.parse_args()
    if sys.version_info < (3, 13):  # noqa: UP036 - installer may run before env setup
        parser.error("MDL requires Python 3.13 or newer")
    if args.build_only:
        build(args.output.expanduser().absolute())
        print(f"Built {args.output}")
        return
    if os.name != "posix":
        parser.error("Command installation supports macOS/Linux; use --build-only on Windows")
    python = sys.executable
    if not args.skip_deps:
        uv = shutil.which("uv")
        if uv is None:
            parser.error("uv is required; install it from https://docs.astral.sh/uv/")
        venv = args.venv_dir.expanduser().absolute()
        environment = os.environ.copy()
        environment.pop("VIRTUAL_ENV", None)
        environment["UV_PROJECT_ENVIRONMENT"] = str(venv)
        subprocess.run(
            [uv, "sync", "--locked", "--no-dev", "--project", str(ROOT)],
            check=True,
            env=environment,
        )
        python = str(venv / "bin" / "python")
    if args.playwright:
        subprocess.run([python, "-m", "playwright", "install", "chromium"], check=True)
    # Smoke-test away from the checkout before replacing the installed command.
    with tempfile.TemporaryDirectory(prefix="mdl-install-") as directory:
        staging = Path(directory)
        bundle = staging / "mdl.py"
        build(bundle, python)
        env = os.environ.copy()
        env.pop("PYTHONPATH", None)
        env["HOME"] = str(staging / "home")
        subprocess.run(
            [python, "-I", str(bundle), "--help"],
            cwd=staging,
            env=env,
            check=True,
            stdout=subprocess.DEVNULL,
        )
        destination = args.bin_dir.expanduser().absolute()
        destination.mkdir(parents=True, exist_ok=True)
        command = destination / "mdl"
        if (command.exists() or command.is_symlink()) and not (
            command.is_symlink() and os.readlink(command) == "mdl.py"
        ):
            parser.error(
                f"Refusing to overwrite existing command: {command}; choose another --bin-dir"
            )
        # Build uses an atomic replacement, leaving an existing working file on failure.
        build(destination / "mdl.py", python)
        if not command.is_symlink():
            command.symlink_to("mdl.py")
    print(f"Installed {destination / 'mdl.py'} (command: {command})")
    print(f"Python: {python}")
    if str(destination) not in os.environ.get("PATH", "").split(os.pathsep):
        print(f"Add {destination} to PATH to run mdl from anywhere.")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, subprocess.CalledProcessError) as exc:
        sys.exit(f"Installation failed: {exc}")
